
apiVersion: apps/v1
kind: Deployment
metadata:
  name: element
  labels:
    app: element
  namespace: matrix
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: element
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: element
    spec:
      securityContext:
       fsGroup: 1337
       runAsUser: 1337
       runAsGroup: 1337
    spec:
      containers:
      - name: element
        image: vectorim/element-web:latest

        ports:
          - containerPort: 80
            name: http
            protocol: TCP

        volumeMounts:
          - name: data
            mountPath: /app/config.json


      volumes:
        - name: data
          hostPath:
            path: /container-files/element/data/config.json

---

apiVersion: v1
kind: Service
metadata:
  name: element
  namespace: matrix

spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: element
  sessionAffinity: None
  type: NodePort


status:
  loadBalancer: {}

---



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-element
  namespace: matrix
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
spec:
  rules:
  - host: element.vels.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: element
            port:
              number: 80
